# FILTERING ARRAYS & MODIFYING ARRAY VALUES

---

## Filtering Arrays

In [1]:
import numpy as np

In [2]:
sales_array = np.array([[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]])
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [3]:
# Evaluate values different from 0
sales_array != 0

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [4]:
# Show values different from 0
sales_array[sales_array != 0]

array([   5,  155,  518, 1827,  616,  317,  325])

---

### Multiple Logical Tests

In [5]:
# Multiple Logical Tests - OR
sales_array[(sales_array == 616) | (sales_array < 100)]

array([  0,   5,   0,   0, 616])

In [6]:
# Multiple Logical Tests - AND
sales_array[(sales_array > 100) & (sales_array < 500)]

array([155, 317, 325])

In [8]:
# PRO TIP: Store complex filtering criteria in a variable

# Working with Boolean Masks
mask = (sales_array > 100) & (sales_array < 500)

sales_array[mask]

array([155, 317, 325])

---

### Filtering arrays based on values of other arrays

In [ ]:
# array 1
sales_array[0, :]

array([  0,   5, 155,   0, 518])

In [ ]:
# Array 2
product_array = np.array(["fruits", "vegetables", "cereal", "dairy", "eggs"])
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [14]:
# Filtering 2 using 1
product_array[sales_array[0, :] > 0]

array(['vegetables', 'cereal', 'eggs'], dtype='<U10')

---

### Modify Array Values

In [15]:
a = sales_array[0, :]
a

array([  0,   5, 155,   0, 518])

In [ ]:
# Method 1: Used to modify a single parameter
a[1] = 30
a

array([  0,  30, 155,   0, 518])

In [19]:
# Method 2: Used to modify many many parameters with the same value
a[a == 0] = -6
a

array([ -6,  30, 155,  -6, 518])

## LABORATORY : Filtering and Modifying Arrays

In [20]:
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
# Show only even numbers
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
even_odd = np.array(["even", "odd"] * 10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [ ]:
# Show only 'odd' values
even_odd[even_odd == "odd"]

array(['odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd',
       'odd'], dtype='<U4')

In [ ]:
# Change even numbers for 0
print(my_array)

my_array[even_odd == "even"] = 0
my_array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [30]:
my_array[2] = 2
my_array

array([ 0,  1,  2,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])