---

# ARRAY FUNCTIONS

---

In [1]:
import numpy as np

In [33]:
sales = np.array([[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]])
sales

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [3]:
np.median(sales)

np.float64(236.0)

In [4]:
np.mean(sales)

np.float64(376.3)

### Percentiles

In [5]:
np.percentile(sales, 50)

np.float64(236.0)

In [6]:
np.percentile(sales, 90)

np.float64(737.0999999999996)

### Unique Values

In [8]:
np.unique(sales)

array([   0,    5,  155,  317,  325,  518,  616, 1827])

### Square Root

In [9]:
np.sqrt(sales)

array([[ 0.        ,  2.23606798, 12.4498996 ,  0.        , 22.75961335],
       [ 0.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

---

## LABORATORY: Array Functions

In [42]:
price = np.array([2.6, 7.2, 6.92, 3.88, 0.78, 2.67, 8.87, 0.23, 5.23, 6.3])

inventory = np.array([79, 22, 20, 48, 8, 76, 12, 16, 5, 64])

product_value = price * inventory
product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [13]:
product_value.sort()
product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [14]:
product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [15]:
reshaped_product_value = product_value.reshape(2, 5)
reshaped_product_value

array([[  3.68,   6.24,  26.15, 106.44, 138.4 ],
       [158.4 , 186.24, 202.92, 205.4 , 403.2 ]])

---

In [16]:
np.median(reshaped_product_value)

np.float64(148.4)

In [ ]:
np.percentile(reshaped_product_value, 50)

np.float64(148.4)

In [18]:
np.percentile(reshaped_product_value, 90)

np.float64(225.17999999999992)

In [19]:
np.percentile(reshaped_product_value, 0)

np.float64(3.68)

In [20]:
np.percentile(reshaped_product_value, 100)

np.float64(403.2)

---

In [21]:
np.sqrt(reshaped_product_value)

array([[ 1.91833261,  2.4979992 ,  5.11370707, 10.3169763 , 11.76435294],
       [12.58570618, 13.64697769, 14.24499912, 14.33178286, 20.07984064]])

In [22]:
np.unique(reshaped_product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

`NOTE`: **Unique Function** tends to be more useful when working with categorical data

---

# SORTING ARRAYS

---

In [24]:
sales

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [ ]:
sort_sales1 = sales.copy()

sort_sales1.sort()  # This method change the array
sort_sales1

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

In [35]:
sales

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

---

In [ ]:
sort_sales2 = sales.copy()

sort_sales2.sort(axis=0)  # This method change the array
sort_sales2

array([[   0,    5,  155,    0,  325],
       [   0, 1827,  616,  317,  518]])

In [38]:
sales

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

---

In [ ]:
sort_sales3 = sales.copy()

sort_sales3.sort(axis=1)  # This method change the array
sort_sales3

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

In [40]:
sales

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

---

## LABORATORY: Array Functions

In [44]:
product_value1 = product_value.copy()
product_value1

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [ ]:
np.sort(product_value1)  # This method DON'T CHANGE the array

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [48]:
product_value1

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])